apiVersion: apps/v1
kind: Deployment
metadata:
  name: husky
  labels:
    app: husky
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: husky
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: husky
    spec:
      containers:
        - image: kemabc123/husky:blue
          imagePullPolicy: Always
          name: husky
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: husky
  labels:
    app: husky
spec:
  type: LoadBalancer
  selector:
    app: husky
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP